// Lightweight slug pairs for every blog post, kept separate from the full
// blogPosts.js content (title/body/FAQ text for 56 posts). Layout.jsx needs
// this on every page (to build hreflang alternates), so importing the full
// blogPosts array here would drag that entire dataset into the main, always
// loaded bundle instead of staying inside the lazy-loaded Blog/BlogPost
// route chunks.
export const blogSlugs = [
    { en: "hot-mama-summer-haircut-with-a-newborn", sl: "hot-mama-summer-frizura-z-dojenckom" },
    { en: "where-to-go-in-ljubljana-after-your-haircut", sl: "kam-v-ljubljani-po-frizuri" },
    { en: "faq", sl: "pogosta-vprasanja" },
    { en: "why-your-hair-smells-bad", sl: "zakaj-lasje-neprijetno-disijo" },
    { en: "how-to-make-your-blowout-last-longer", sl: "kako-podaljsati-obstojnost-fen-frizure" },
    { en: "how-to-speed-up-hair-growth", sl: "kako-pospesiti-rast-las" },
    { en: "how-to-get-to-our-salon", sl: "kako-do-nasega-salona" },
    { en: "spring-hairstyles-for-busy-working-women", sl: "pomladne-frizure-za-zaposlene-zenske" },
    { en: "why-you-should-never-peel-polish-off-your-nails", sl: "zakaj-nikoli-ne-smes-puliti-laka-dol-iz-nohta" },
    { en: "how-to-keep-your-nails-strong-between-salon-visits", sl: "kako-ohraniti-mocne-nohte-med-obiski-salona" },
    { en: "the-most-common-hair-care-mistakes", sl: "najpogostejse-napake-pri-negi-las" },
    { en: "how-your-hair-affects-your-confidence", sl: "tvoji-lasje-vplivajo-na-samozavest" },
    { en: "what-to-ask-your-stylist-before-they-start", sl: "kaj-vprasati-stilista-preden-zacne" },
    { en: "restore-your-tired-hair", sl: "obnovi-utrujene-lase" },
    { en: "new-year-new-hair", sl: "novo-leto-novi-lasje" },
    { en: "why-hair-color-fades-too-fast", sl: "zakaj-barva-za-lase-prehitro-zbledi" },
    { en: "christmas-hair", sl: "bozicni-lasje" },
    { en: "how-to-care-for-your-hair-after-a-night-out", sl: "kako-negovati-lase-po-zabavi" },
    { en: "holiday-hairstyles-at-status-kay", sl: "praznicne-frizure-v-status-kay" },
    { en: "how-to-repair-hair-damaged-by-straightening", sl: "kako-popraviti-poskodovane-lase-zaradi-likanja" },
    { en: "winter-hair-care-tips", sl: "nasveti-za-zimske-lase" },
    { en: "blondorplex", sl: "blondorplex" },
    { en: "wellaplex", sl: "wellaplex" },
    { en: "how-to-revive-damaged-curls", sl: "kako-ponovno-oziviti-poskodovane-kodre" },
    { en: "why-you-should-use-nail-oil-every-day", sl: "zakaj-uporabljati-olje-za-nohte-vsak-dan" },
    { en: "what-is-formaldehyde", sl: "kaj-je-formaldehid" },
    { en: "why-its-good-to-let-your-nails-breathe", sl: "zakaj-je-dobro-pustiti-nohte-da-dihajo" },
    { en: "how-to-choose-the-right-hair-mask", sl: "kako-izbrati-masko-za-lase" },
    { en: "blow-drying-with-ibiza-brushes", sl: "feniranje-s-krtacami-ibiza" },
    { en: "the-basics-of-heat-styling", sl: "osnove-toplotnega-oblikovanja" },
    { en: "5-tricks-for-healthy-shiny-hair", sl: "5-trikov-za-zdrave-in-sijoce-lase" },
    { en: "simple-hairstyles-for-busy-professionals", sl: "preproste-priceske-za-zaposlene-profesionalce" },
    { en: "cutting-your-hair-by-the-moon", sl: "strizenje-glede-na-luno" },
    { en: "hairstyling-before-the-machines", sl: "strizenje-pred-stroji" },
    { en: "why-we-dont-cut-your-cuticles", sl: "zakaj-obnohtne-kozice-ne-rezemo" },
    { en: "dry-shampoo-done-right", sl: "suhi-sampon" },
    { en: "hair-care-through-the-seasons", sl: "negovanje-las-v-razlicnih-sezonah" },
    { en: "first-time-visiting-us", sl: "prvic-pri-nas" },
    { en: "why-regular-haircuts-are-essential", sl: "zakaj-je-redno-strizenje-nujno" },
    { en: "how-to-maintain-salon-perfect-hair-at-home", sl: "kako-doma-ohraniti-popolne-lase" },
    { en: "balayage-or-highlights", sl: "balayage-ali-pramena" },
    { en: "how-to-choose-the-perfect-hair-color", sl: "kako-izbrati-popolno-barvo-las" },
    { en: "why-toning-is-the-secret-to-long-lasting-color", sl: "toniranje" },
    { en: "two-step-hair-coloring", sl: "dvostopenjsko-barvanje" },
    { en: "all-about-highlights", sl: "prameni" },
    { en: "spring-hair-trends-2025", sl: "pomladni-trendi-2025" },
    { en: "meet-daisy", sl: "spoznajte-daisy" },
    { en: "tourists-and-expats-welcome", sl: "turisti-in-tujci-dobrodosli" },
    { en: "haircut-styles", sl: "strizenje" },
    { en: "hair-coloring-techniques", sl: "tehnike-barvanja" },
    { en: "about-status-kay-salon", sl: "o-status-kay-salonu" }
];
